### ISSUE TITLE
A flip functionality for cards on services page 

### ISSUE THREAD

**Issue by PJSalter** [sonianb/agency-website#2]
- website development - what the company does 
- E-commerse  - Another feature
- wordpress development - Another feature
- three cards in total
-additional functionality so that once the user hovers over one of the cards then it will flip with detailed info about the services of the agency
<img width="695" alt="Screenshot 2022-01-21 at 18 00 17" src="https://user-images.githubusercontent.com/45575016/150578567-932c9a84-f625-4ed4-9cff-fb0fc8110e98.png">

**Comment by sonianb** [comment]
Closed by #8
