### ISSUE TITLE
Compliments

### ISSUE THREAD

**Issue by joe-dev-public** [sonianb/agency-website#32]
- Rotating cards for "our services"
- Visually interesting main nav
- (and more! :)

**Comment by HusJAW** [comment]
love the design and my favourite part is the rotating cards it was really smooth 

and the overall design was unique and nice

**Comment by minju25kim** [comment]
The navigation design idea is really great to view the menus in the website. 👍

**Comment by sonianb** [comment]
Thank you @joe-dev-public, @HusJAW, @kmj673 ❤️
